import JSZip from 'jszip'
import { getStandaloneEngineSource } from './standaloneEngine'
import type { GameProject } from '../types'

function slug(name: string) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'my-game'
}

export async function generateGameZip(project: GameProject): Promise<Blob> {
  const zip = new JSZip()
  const title = project.settings.title || 'My Adventure Game'
  const name = slug(title)
  const w = project.settings.resolutionWidth || 1280
  const h = project.settings.resolutionHeight || 720

  // ── package.json ────────────────────────────────────────────────────────────
  zip.file('package.json', JSON.stringify({
    name,
    version: project.settings.version || '1.0.0',
    description: project.settings.description || '',
    private: true,
    type: 'module',
    scripts: {
      dev: 'vite',
      build: 'vite build',
      preview: 'vite preview',
    },
    devDependencies: {
      vite: '^5.0.0',
    },
  }, null, 2))

  // ── vite.config.js ──────────────────────────────────────────────────────────
  zip.file('vite.config.js', `import { defineConfig } from 'vite'

export default defineConfig({
  build: {
    outDir: 'dist',
    emptyOutDir: true,
  },
})
`)

  // ── index.html ──────────────────────────────────────────────────────────────
  zip.file('index.html', `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title}</title>
    <link rel="stylesheet" href="/src/style.css" />
    <script src="https://cdn.jsdelivr.net/npm/phaser@3.80.1/dist/phaser.min.js"></script>
  </head>
  <body>
    <div id="app">
      <canvas id="game-canvas" width="${w}" height="${h}"></canvas>
    </div>
    <script type="module" src="/src/main.js"></script>
  </body>
</html>
`)

  // ── src/style.css ───────────────────────────────────────────────────────────
  zip.file('src/style.css', `*, *::before, *::after { box-sizing: border-box; }
html, body { margin: 0; padding: 0; background: #000; height: 100%; overflow: hidden; }
#app {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100vw;
  height: 100vh;
}
#game-canvas {
  display: block;
  max-width: 100%;
  max-height: 100%;
  object-fit: contain;
}
`)

  // ── src/engine.js ────────────────────────────────────────────────────────────
  zip.file('src/engine.js', getStandaloneEngineSource())

  // ── src/game-data.json ───────────────────────────────────────────────────────
  zip.file('src/game-data.json', JSON.stringify(project, null, 2))

  // ── mini-game source files ───────────────────────────────────────────────────
  for (const mg of project.miniGames ?? []) {
    if (mg.source) {
      zip.file(`src/minigames/${mg.id}.js`, mg.source)
    }
  }

  // ── src/main.js ──────────────────────────────────────────────────────────────
  zip.file('src/main.js', `import { GameEngine } from './engine.js'
import gameData from './game-data.json'

const canvas = document.getElementById('game-canvas')
if (!canvas) throw new Error('Canvas element not found')

const engine = new GameEngine(canvas, gameData)
engine.start()
`)

  // ── README.md ────────────────────────────────────────────────────────────────
  zip.file('README.md', `# ${title}

Generated by **Adventure Game Builder**.

## Running locally

\`\`\`bash
npm install
npm run dev
\`\`\`

Then open http://localhost:5173 in your browser.

## Building for production

\`\`\`bash
npm run build
\`\`\`

The \`dist/\` folder contains static HTML + JS files ready to deploy on any HTTP server.
`)

  return zip.generateAsync({ type: 'blob' })
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
