/**
 * Returns the source of the standalone game engine as an ES-module string.
 * This is embedded verbatim as engine.js inside the exported Vite project ZIP.
 * It mirrors GameRuntime.ts with no external imports (plain JS, no TS).
 */
export function getStandaloneEngineSource(): string {
  return `
// Adventure Game Engine — standalone ES module (generated by Adventure Game Builder)

const CHAR_SPEED = 250; // scene px / second

export class GameEngine {
  constructor(canvas, project) {
    this.canvas = canvas;
    this.ctx = canvas.getContext('2d');
    this.project = project;
    this.imageCache = new Map();
    this.objectVisibility = new Map();
    this.frameId = null;
    this.lastFrameTime = 0;
    this.state = this._freshState();
    this._boundClick = this._handleClick.bind(this);
    this._boundMove = this._handleMouseMove.bind(this);
  }

  _freshState() {
    return {
      currentSceneId: this.project.settings?.startingSceneId || this.project.scenes[0]?.id || '',
      variables: {},
      visitedScenes: [],
      running: false,
      dialogText: null,
      dialogCallback: null,
      character: null,
    };
  }

  start() {
    if (this.state.running) return;
    this.state.running = true;
    this.lastFrameTime = 0;
    this.canvas.addEventListener('click', this._boundClick);
    this.canvas.addEventListener('mousemove', this._boundMove);
    this._loadScene(this.state.currentSceneId);
    this._loop();
  }

  stop() {
    this.state.running = false;
    this.canvas.removeEventListener('click', this._boundClick);
    this.canvas.removeEventListener('mousemove', this._boundMove);
    if (this.frameId !== null) { cancelAnimationFrame(this.frameId); this.frameId = null; }
  }

  reset() {
    this.stop();
    this.objectVisibility.clear();
    this.imageCache.clear();
    this.state = this._freshState();
    this.start();
  }

  _loadScene(sceneId) {
    this.state.currentSceneId = sceneId;
    if (!this.state.visitedScenes.includes(sceneId)) this.state.visitedScenes.push(sceneId);
    const scene = this.project.scenes.find(s => s.id === sceneId);
    if (scene) {
      if (scene.backgroundImageUrl) this._loadImage(scene.backgroundImageUrl);
      scene.objects.forEach(o => { if (o.imageUrl) this._loadImage(o.imageUrl); });
      // Pre-load character sprite sheets
      const mc = this.project.mainCharacter;
      if (mc) {
        ['up','down','left','right'].forEach(dir => {
          const sheet = this._getCharSheet(dir);
          if (sheet?.imageUrl) this._loadImage(sheet.imageUrl);
        });
      }
      // Init character from scene placement
      const cp = scene.characterPlacement;
      if (cp?.visible && mc) {
        const facing = cp.facing || mc.defaultFacing || 'down';
        this.state.character = {
          x: cp.x, y: cp.y,
          targetX: null, targetY: null,
          facing, moving: false,
          animFrame: this._getAnimStartFrame(facing),
          animTimer: 0,
        };
      } else {
        this.state.character = null;
      }
    }
    this.project.events
      .filter(e => e.sceneId === sceneId && e.trigger === 'enter' && e.enabled)
      .forEach(ev => this._execEvent(ev));
  }

  _loop() {
    if (!this.state.running) return;
    const now = performance.now();
    const dt = this.lastFrameTime ? Math.min(now - this.lastFrameTime, 100) : 16;
    this.lastFrameTime = now;
    this._updateCharacter(dt);
    this._render();
    this.frameId = requestAnimationFrame(() => this._loop());
  }

  _updateCharacter(dt) {
    const char = this.state.character;
    if (!char || !char.moving || char.targetX === null || char.targetY === null) return;
    const dx = char.targetX - char.x, dy = char.targetY - char.y;
    const dist = Math.sqrt(dx*dx + dy*dy);
    if (dist < 3) {
      char.x = char.targetX; char.y = char.targetY;
      char.targetX = null; char.targetY = null;
      char.moving = false;
      char.animFrame = this._getAnimStartFrame(char.facing);
      char.animTimer = 0;
      return;
    }
    // Facing from dominant axis
    if (Math.abs(dx) >= Math.abs(dy)) { char.facing = dx > 0 ? 'right' : 'left'; }
    else { char.facing = dy > 0 ? 'down' : 'up'; }
    const step = CHAR_SPEED * (dt / 1000);
    const ratio = Math.min(step / dist, 1);
    char.x += dx * ratio; char.y += dy * ratio;
    // Advance anim frame
    const animDef = this._getCharAnim(char.facing);
    if (animDef && animDef.fps > 0) {
      const frameMs = 1000 / animDef.fps;
      char.animTimer += dt;
      while (char.animTimer >= frameMs) {
        char.animTimer -= frameMs;
        char.animFrame++;
        if (char.animFrame > animDef.endFrame) char.animFrame = animDef.startFrame;
      }
    }
  }

  _render() {
    const { canvas, ctx } = this;
    const scene = this.project.scenes.find(s => s.id === this.state.currentSceneId);
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    if (!scene) {
      ctx.fillStyle = '#1a1a2e'; ctx.fillRect(0,0,canvas.width,canvas.height);
      ctx.fillStyle = '#e2e8f0'; ctx.font = '20px sans-serif';
      ctx.textAlign = 'center'; ctx.textBaseline = 'middle';
      ctx.fillText('No scene', canvas.width/2, canvas.height/2);
      return;
    }
    const sx = canvas.width / scene.width, sy = canvas.height / scene.height;
    ctx.save(); ctx.scale(sx, sy);
    ctx.fillStyle = scene.backgroundColor || '#000';
    ctx.fillRect(0, 0, scene.width, scene.height);
    if (scene.backgroundImageUrl) {
      const img = this.imageCache.get(scene.backgroundImageUrl);
      if (img) ctx.drawImage(img, 0, 0, scene.width, scene.height);
    }
    [...scene.objects].sort((a,b) => a.zIndex - b.zIndex).forEach(obj => {
      const vis = this.objectVisibility.has(obj.id) ? this.objectVisibility.get(obj.id) : obj.visible;
      if (!vis) return;
      ctx.save(); ctx.globalAlpha = obj.opacity;
      const img = obj.imageUrl ? this.imageCache.get(obj.imageUrl) : null;
      if (img) {
        ctx.drawImage(img, obj.x, obj.y, obj.width, obj.height);
      } else {
        const colors = { sprite:'#4f46e5', character:'#7c3aed', item:'#d97706', hotspot:'rgba(99,102,241,0.15)', background:'#1e293b' };
        ctx.fillStyle = colors[obj.type] || '#4f46e5';
        ctx.fillRect(obj.x, obj.y, obj.width, obj.height);
        if (obj.type !== 'hotspot') {
          ctx.fillStyle = '#fff'; ctx.font = '14px sans-serif';
          ctx.textAlign = 'center'; ctx.textBaseline = 'middle';
          ctx.fillText(obj.name, obj.x+obj.width/2, obj.y+obj.height/2);
        }
      }
      ctx.restore();
    });
    // Draw character
    this._renderCharacter();
    ctx.restore();
    if (this.state.dialogText) this._renderDialog();
  }

  _renderCharacter() {
    const char = this.state.character;
    const mc = this.project.mainCharacter;
    if (!char || !mc) return;
    const { ctx } = this;
    const cw = mc.width, ch = mc.height;
    const sheet = this._getCharSheet(char.facing);
    const img = sheet ? this.imageCache.get(sheet.imageUrl) : null;
    if (img && sheet) {
      const col = char.animFrame % sheet.cols;
      const row = Math.floor(char.animFrame / sheet.cols);
      ctx.drawImage(img,
        col * sheet.frameWidth, row * sheet.frameHeight, sheet.frameWidth, sheet.frameHeight,
        Math.round(char.x), Math.round(char.y), cw, ch
      );
    } else {
      ctx.save();
      ctx.fillStyle = 'rgba(99,102,241,0.7)';
      ctx.fillRect(char.x, char.y, cw, ch);
      ctx.fillStyle = '#fff';
      ctx.font = Math.min(12, ch*0.18)+'px sans-serif';
      ctx.textAlign = 'center'; ctx.textBaseline = 'middle';
      ctx.fillText(mc.name || 'Player', char.x+cw/2, char.y+ch/2);
      ctx.restore();
    }
  }

  _renderDialog() {
    const { canvas, ctx } = this;
    const pad = 24, bh = 130, by = canvas.height - bh - 12;
    ctx.fillStyle = 'rgba(0,0,0,0.88)'; ctx.fillRect(8,by,canvas.width-16,bh);
    ctx.strokeStyle = '#6366f1'; ctx.lineWidth = 2; ctx.strokeRect(8,by,canvas.width-16,bh);
    const fs = Math.max(12, Math.min(16, canvas.width/50));
    ctx.font = fs+'px sans-serif'; ctx.fillStyle = '#e2e8f0';
    ctx.textAlign = 'left'; ctx.textBaseline = 'top';
    const mw = canvas.width-16-pad*2, words = this.state.dialogText.split(' ');
    let line='', ly=by+pad, lh=fs+6;
    words.forEach(w => {
      const t = line+w+' ';
      if (ctx.measureText(t).width > mw && line) { ctx.fillText(line.trim(), 8+pad, ly); line=w+' '; ly+=lh; }
      else line=t;
    });
    if (line.trim()) ctx.fillText(line.trim(), 8+pad, ly);
    ctx.fillStyle='#6366f1'; ctx.font='12px sans-serif'; ctx.textAlign='right'; ctx.textBaseline='bottom';
    ctx.fillText('\\u25b6 Click to continue', canvas.width-16, by+bh-8);
  }

  _scenePos(e) {
    const r = this.canvas.getBoundingClientRect();
    const cx = (e.clientX-r.left)*(this.canvas.width/r.width);
    const cy = (e.clientY-r.top)*(this.canvas.height/r.height);
    const scene = this.project.scenes.find(s=>s.id===this.state.currentSceneId);
    if (!scene) return {x:cx,y:cy};
    return { x: cx/(this.canvas.width/scene.width), y: cy/(this.canvas.height/scene.height) };
  }

  _handleClick(e) {
    if (this.state.dialogText) {
      this.state.dialogText=null;
      const cb=this.state.dialogCallback; this.state.dialogCallback=null; if(cb)cb();
      return;
    }
    const pos = this._scenePos(e);
    const scene = this.project.scenes.find(s=>s.id===this.state.currentSceneId);
    if (!scene) return;
    const obj = this._objAt(scene, pos.x, pos.y);
    if (obj) {
      this.project.events
        .filter(ev=>ev.sceneId===scene.id&&ev.objectId===obj.id&&ev.trigger==='click'&&ev.enabled)
        .forEach(ev=>this._execEvent(ev));
      return;
    }
    // No object — walk character to click
    const char = this.state.character;
    const mc = this.project.mainCharacter;
    if (char && mc) {
      char.targetX = pos.x - mc.width / 2;
      char.targetY = pos.y - mc.height / 2;
      char.moving = true;
    }
  }

  _handleMouseMove(e) {
    if (this.state.dialogText) return;
    const pos = this._scenePos(e);
    const scene = this.project.scenes.find(s=>s.id===this.state.currentSceneId);
    if (!scene) return;
    this.canvas.style.cursor = this._objAt(scene, pos.x, pos.y) ? 'pointer' : 'default';
  }

  _objAt(scene, x, y) {
    return [...scene.objects]
      .filter(o => (this.objectVisibility.has(o.id)?this.objectVisibility.get(o.id):o.visible))
      .sort((a,b)=>b.zIndex-a.zIndex)
      .find(o=>x>=o.x&&x<=o.x+o.width&&y>=o.y&&y<=o.y+o.height)||null;
  }

  _execEvent(ev) { ev.actions.forEach(a=>this._execAction(a)); }

  _execAction(action) {
    switch(action.type) {
      case 'navigate_scene': {
        const s=this.project.scenes.find(s=>s.id===action.value||s.name===action.value);
        if(s) this._loadScene(s.id); break;
      }
      case 'show_dialog': this.state.dialogText=action.value; break;
      case 'set_variable': {
        const i=action.value.indexOf('=');
        if(i!==-1) this.state.variables[action.value.slice(0,i).trim()]=action.value.slice(i+1).trim();
        break;
      }
      case 'show_object': this.objectVisibility.set(action.value,true); break;
      case 'hide_object': this.objectVisibility.set(action.value,false); break;
      case 'play_sound': {
        const a=this.project.assets?.find(a=>a.id===action.value||a.name===action.value);
        if(a?.url) new Audio(a.url).play().catch(()=>{});
        break;
      }
    }
  }

  _getCharSheet(facing) {
    const mc = this.project.mainCharacter;
    if (!mc) return null;
    const animCfg = mc.animations?.[facing];
    if (!animCfg?.spriteSheetId) return null;
    return this.project.spriteSheets?.find(s => s.id === animCfg.spriteSheetId) || null;
  }

  _getCharAnim(facing) {
    const mc = this.project.mainCharacter;
    if (!mc) return null;
    const animCfg = mc.animations?.[facing];
    const sheet = this._getCharSheet(facing);
    if (!sheet || !animCfg?.animationId) return null;
    return sheet.animations.find(a => a.id === animCfg.animationId) || null;
  }

  _getAnimStartFrame(facing) {
    return this._getCharAnim(facing)?.startFrame ?? 0;
  }

  _loadImage(url) {
    if (this.imageCache.has(url)) return;
    const img=new Image(); img.onload=()=>this.imageCache.set(url,img); img.src=url;
  }
}
`.trim()
}
