/**
 * Returns the source of the standalone game engine as an ES-module string.
 * This is embedded verbatim as engine.js inside the exported Vite project ZIP.
 * It mirrors GameRuntime.ts with no external imports (plain JS, no TS).
 */
export function getStandaloneEngineSource(): string {
  return `
// Adventure Game Engine — standalone ES module (generated by Adventure Game Builder)

// ── Pathfinding (A* + string-pulling / Simple Stupid Funnel Algorithm) ───────

const GRID_CELL = 16;

// 2D cross product (O→A)×(O→B) in screen coords (y-down).
// >0 = B is clockwise (right) of O→A; <0 = counter-clockwise (left).
function cross2D(ox,oy,ax,ay,bx,by){return(ax-ox)*(by-oy)-(ay-oy)*(bx-ox);}

// Build portal sequence from A* cell path.
// Each portal is the shared edge between consecutive cells, L/R relative to travel direction.
// Diagonal steps produce a degenerate portal (corner point, L===R).
// Last portal is always the exact destination point.
function buildPortals(cells,endX,endY){
  const G=GRID_CELL,portals=[];
  for(let i=1;i<cells.length;i++){
    const a=cells[i-1],b=cells[i];
    const dc=b.col-a.col,dr=b.row-a.row;
    let lx,ly,rx,ry;
    if(dc===1&&dr===0){lx=b.col*G;ly=a.row*G;rx=b.col*G;ry=(a.row+1)*G;}
    else if(dc===-1&&dr===0){lx=a.col*G;ly=(a.row+1)*G;rx=a.col*G;ry=a.row*G;}
    else if(dc===0&&dr===1){lx=(a.col+1)*G;ly=b.row*G;rx=a.col*G;ry=b.row*G;}
    else if(dc===0&&dr===-1){lx=a.col*G;ly=a.row*G;rx=(a.col+1)*G;ry=a.row*G;}
    else{lx=rx=Math.max(a.col,b.col)*G;ly=ry=Math.max(a.row,b.row)*G;}
    portals.push({lx,ly,rx,ry});
  }
  portals.push({lx:endX,ly:endY,rx:endX,ry:endY});
  return portals;
}

// Simple Stupid Funnel Algorithm — O(n) string-pull through the portal sequence.
function stringPull(startX,startY,portals){
  if(!portals.length) return [{x:startX,y:startY}];
  const result=[{x:startX,y:startY}];
  let ax=startX,ay=startY,flx=startX,fly=startY,frx=startX,fry=startY,iL=0,iR=0;
  for(let i=0;i<portals.length;i++){
    const {lx,ly,rx,ry}=portals[i];
    // Try tighten right boundary
    if(cross2D(ax,ay,frx,fry,rx,ry)<=0){
      if((ax===frx&&ay===fry)||cross2D(ax,ay,flx,fly,rx,ry)>=0){frx=rx;fry=ry;iR=i;}
      else{result.push({x:flx,y:fly});ax=flx;ay=fly;const rs=iL+1;flx=ax;fly=ay;frx=ax;fry=ay;iL=rs;iR=rs;i=rs-1;continue;}
    }
    // Try tighten left boundary
    if(cross2D(ax,ay,flx,fly,lx,ly)>=0){
      if((ax===flx&&ay===fly)||cross2D(ax,ay,frx,fry,lx,ly)<=0){flx=lx;fly=ly;iL=i;}
      else{result.push({x:frx,y:fry});ax=frx;ay=fry;const rs=iR+1;flx=ax;fly=ay;frx=ax;fry=ay;iL=rs;iR=rs;i=rs-1;continue;}
    }
  }
  const end=portals[portals.length-1],last=result[result.length-1];
  if(last.x!==end.lx||last.y!==end.ly) result.push({x:end.lx,y:end.ly});
  return result;
}

function findPath(blockedZones, sceneWidth, sceneHeight, fromX, fromY, toX, toY, charWidth=0, charHeight=0) {
  const cols = Math.ceil(sceneWidth / GRID_CELL);
  const rows = Math.ceil(sceneHeight / GRID_CELL);
  const halfW=charWidth/2, halfH=charHeight/2;
  const walkable = Array.from({length: rows}, () => new Array(cols).fill(true));
  for (const z of blockedZones) {
    const c0=Math.max(0,Math.round((z.x-halfW)/GRID_CELL)), c1=Math.min(cols,Math.round((z.x+z.width+halfW)/GRID_CELL));
    const r0=Math.max(0,Math.round((z.y-halfH)/GRID_CELL)), r1=Math.min(rows,Math.round((z.y+z.height+halfH)/GRID_CELL));
    for (let r=r0;r<r1;r++) for (let c=c0;c<c1;c++) walkable[r][c]=false;
  }
  const cc=(c)=>Math.max(0,Math.min(cols-1,c)), cr=(r)=>Math.max(0,Math.min(rows-1,r));
  const sC=cc(Math.round(fromX/GRID_CELL)), sR=cr(Math.round(fromY/GRID_CELL));
  let eC=cc(Math.round(toX/GRID_CELL)), eR=cr(Math.round(toY/GRID_CELL));
  walkable[sR][sC]=true;
  let effToX=toX,effToY=toY;
  if (!walkable[eR][eC]) {
    const dr=eR-sR,dc=eC-sC,steps=Math.max(Math.abs(dr),Math.abs(dc),1);
    let found=false;
    for(let step=steps;step>=1;step--){
      const r=Math.round(sR+dr*(step/steps)),c=Math.round(sC+dc*(step/steps));
      if(r<0||r>=rows||c<0||c>=cols) continue;
      if(walkable[r][c]){eR=r;eC=c;found=true;effToX=dc>0?(c+1)*GRID_CELL:dc<0?c*GRID_CELL:c*GRID_CELL+GRID_CELL/2;effToY=dr>0?(r+1)*GRID_CELL:dr<0?r*GRID_CELL:r*GRID_CELL+GRID_CELL/2;break;}
    }
    if(!found){
      let best=Infinity;
      for (let r=0;r<rows;r++) for (let c=0;c<cols;c++) {
        if (!walkable[r][c]) continue;
        const d=(r-eR)**2+(c-eC)**2; if(d<best){best=d;eR=r;eC=c;}
      }
    }
  }
  if (sR===eR&&sC===eC) return [{x:toX,y:toY}];
  const key=(r,c)=>r*cols+c, h=(r,c)=>Math.sqrt((r-eR)**2+(c-eC)**2);
  const open=new Map(), closed=new Set(), allNodes=new Map();
  const root={g:0,h:h(sR,sC),f:0,row:sR,col:sC,parent:null}; root.f=root.h;
  open.set(key(sR,sC),root); allNodes.set(key(sR,sC),root);
  const DIRS=[[-1,0],[1,0],[0,-1],[0,1],[-1,-1],[-1,1],[1,-1],[1,1]];
  const S2=Math.SQRT2; let endNode=null;
  while (open.size>0) {
    let cur=null; for (const n of open.values()) if(!cur||n.f<cur.f) cur=n;
    if (!cur) break;
    if (cur.row===eR&&cur.col===eC){endNode=cur;break;}
    open.delete(key(cur.row,cur.col)); closed.add(key(cur.row,cur.col));
    for (let i=0;i<DIRS.length;i++) {
      const [dr,dc]=DIRS[i], nr=cur.row+dr, nc=cur.col+dc;
      if(nr<0||nr>=rows||nc<0||nc>=cols||!walkable[nr][nc]||closed.has(key(nr,nc))) continue;
      if(dr!==0&&dc!==0&&(!walkable[cur.row+dr][cur.col]||!walkable[cur.row][cur.col+dc])) continue;
      const g=cur.g+(i<4?1:S2), nk=key(nr,nc), ex=open.get(nk);
      if(ex&&ex.g<=g) continue;
      const node={g,h:h(nr,nc),f:0,row:nr,col:nc,parent:cur}; node.f=node.g+node.h;
      open.set(nk,node); allNodes.set(nk,node);
    }
  }
  if (!endNode) {
    const dr=eR-sR,dc=eC-sC,steps=Math.max(Math.abs(dr),Math.abs(dc),1);
    for(let step=steps;step>=1;step--){
      const r=Math.round(sR+dr*(step/steps)),c=Math.round(sC+dc*(step/steps));
      if(r<0||r>=rows||c<0||c>=cols) continue;
      if(!walkable[r][c]) continue;
      if(r===sR&&c===sC) break;
      const nd=allNodes.get(key(r,c));
      if(nd&&closed.has(key(r,c))){endNode=nd;effToX=dc>0?(c+1)*GRID_CELL:dc<0?c*GRID_CELL:c*GRID_CELL+GRID_CELL/2;effToY=dr>0?(r+1)*GRID_CELL:dr<0?r*GRID_CELL:r*GRID_CELL+GRID_CELL/2;break;}
    }
    if(!endNode) return [];
  }
  const cells=[]; let n=endNode;
  while(n){cells.unshift(n);n=n.parent;}
  return stringPull(fromX,fromY,buildPortals(cells,effToX,effToY));
}

// ── Game Engine ───────────────────────────────────────────────────────────────

const CHAR_SPEED = 250;

export class GameEngine {
  constructor(canvas, project) {
    this.canvas = canvas;
    this.canvas.draggable = false;
    this.ctx = canvas.getContext('2d');
    this.project = project;
    this.imageCache = new Map();
    this.objectVisibility = new Map();
    this.removedObjects = new Set();
    this.activeCollisions = new Set();
    this.repeatCounts = new Map();
    this.frameId = null;
    this.lastFrameTime = 0;
    this.titleScreenButtonRects = [];
    this.questButtonRect = {x:0,y:0,w:0,h:0};
    this.questLogCloseRect = {x:0,y:0,w:0,h:0};
    this.state = this._freshState();
    this._boundClick = this._handleClick.bind(this);
    this._boundMove = this._handleMouseMove.bind(this);
    this._boundKeyDown = this._handleKeyDown.bind(this);
    this._boundKeyUp = this._handleKeyUp.bind(this);
    this.activeKeys = new Set();
  }

  _freshState() {
    const ts=this.project.titleScreen;
    const hasTitleScreen=!!(ts?.titleText||(ts?.buttons&&ts.buttons.length>0));
    return {
      currentSceneId: this.project.settings?.startingSceneId || this.project.scenes[0]?.id || '',
      currentStageId: null,
      variables: {},
      visitedScenes: [],
      running: false,
      dialogText: null,
      dialogCallback: null,
      character: null,
      activeHotspots: new Set(),
      activeTeleportZones: new Set(),
      cinematic: null,
      npcStates: new Map(),
      showTitleScreen: hasTitleScreen,
      miniGame: null,
      activeQuestIds: [],
      completedQuestIds: [],
      questLogOpen: false,
    };
  }

  start() {
    if (this.state.running) return;
    this.state.running = true;
    this.lastFrameTime = 0;
    this.canvas.addEventListener('click', this._boundClick);
    this.canvas.addEventListener('mousemove', this._boundMove);
    window.addEventListener('keydown', this._boundKeyDown);
    window.addEventListener('keyup', this._boundKeyUp);
    const gameStartEvs=(this.project.events||[]).filter(e=>this._evTriggers(e).includes('game_start')&&e.enabled);
    gameStartEvs.forEach(e=>this._execEvent(e));
    this._initStageForScene(this.state.currentSceneId);
    if(this.state.showTitleScreen){
      const ts=this.project.titleScreen;
      if(ts?.backgroundImageUrl) this._loadImage(ts.backgroundImageUrl);
    } else {
      this._loadScene(this.state.currentSceneId,undefined,true);
    }
    this._loop();
  }

  _initStageForScene(sceneId) {
    const stage=(this.project.stages||[]).find(s=>(s.sceneIds||[]).includes(sceneId));
    if(!stage||stage.id===this.state.currentStageId) return;
    this.state.currentStageId=stage.id;
    for(const v of stage.variables||[]){
      const val=v.type==='number'?(Number(v.defaultValue)||0):v.type==='boolean'?(v.defaultValue==='true'):v.defaultValue;
      this.state.variables[v.name]=val;
    }
    const stageStartEvs=(this.project.events||[]).filter(e=>this._evTriggers(e).includes('stage_start')&&e.stageId===stage.id&&e.enabled);
    stageStartEvs.forEach(e=>this._execEvent(e));
  }

  _applyVarExpr(expr) {
    const ai=expr.indexOf('+='),si=expr.indexOf('-=');
    if(ai!==-1){const k=expr.slice(0,ai).trim(),n=Number(expr.slice(ai+2).trim());if(k&&!isNaN(n))this.state.variables[k]=(Number(this.state.variables[k]??0)+n);return;}
    if(si!==-1){const k=expr.slice(0,si).trim(),n=Number(expr.slice(si+2).trim());if(k&&!isNaN(n))this.state.variables[k]=(Number(this.state.variables[k]??0)-n);return;}
    const ei=expr.indexOf('=');if(ei!==-1){const k=expr.slice(0,ei).trim(),v=expr.slice(ei+1).trim();if(k)this.state.variables[k]=v;}
  }

  _evaluateGoals() {
    const stageId=this.state.currentStageId;
    if(!stageId) return;
    const goals=(this.project.goals||[]).filter(g=>g.stageId===stageId&&!g.completed);
    for(const goal of goals){
      if(this._checkGoalConditions(goal)){this._completeGoal(goal);return;}
    }
  }

  _checkGoalConditions(goal) {
    if(!goal.conditions.length) return false;
    const results=goal.conditions.map(c=>this._checkCondition(c));
    return goal.logic==='AND'?results.every(Boolean):results.some(Boolean);
  }

  _checkCondition(cond) {
    const raw=this.state.variables[cond.target];
    const sv=raw!==undefined?String(raw):'';
    switch(cond.operator){
      case 'equals':       return sv===cond.value;
      case 'not_equals':   return sv!==cond.value;
      case 'greater_than': return Number(sv)>Number(cond.value);
      case 'less_than':    return Number(sv)<Number(cond.value);
      case 'contains':     return sv.includes(cond.value);
      default:             return false;
    }
  }

  _completeGoal(goal) {
    goal.completed=true;
    switch(goal.completionAction){
      case 'advance_stage':{
        const stages=[...(this.project.stages||[])].sort((a,b)=>a.order-b.order);
        const idx=stages.findIndex(s=>s.id===this.state.currentStageId);
        const next=stages[idx+1];
        if(next){
          this.state.currentStageId=next.id;
          for(const v of next.variables||[]){
            const val=v.type==='number'?(Number(v.defaultValue)||0):v.type==='boolean'?(v.defaultValue==='true'):v.defaultValue;
            this.state.variables[v.name]=val;
          }
          if(next.startingSceneId) this._loadScene(next.startingSceneId,undefined,true);
        }
        break;
      }
      case 'end_game':
        this.state.dialogText=goal.completionValue||'You completed the game!';
        break;
      case 'show_dialog':
        this.state.dialogText=goal.completionValue;
        break;
    }
  }

  stop() {
    this.state.running = false;
    this.canvas.removeEventListener('click', this._boundClick);
    this.canvas.removeEventListener('mousemove', this._boundMove);
    window.removeEventListener('keydown', this._boundKeyDown);
    window.removeEventListener('keyup', this._boundKeyUp);
    if (this.frameId !== null) { cancelAnimationFrame(this.frameId); this.frameId = null; }
  }

  reset() {
    this.stop();
    this.objectVisibility.clear();
    this.removedObjects.clear();
    this.activeCollisions.clear();
    this.repeatCounts.clear();
    this.imageCache.clear();
    this.state = this._freshState();
    this.start();
  }

  _loadScene(sceneId, entryOverride, stageStart=false) {
    this.state.currentSceneId = sceneId;
    this.state.activeHotspots = new Set();
    this.state.activeTeleportZones = new Set();
    if (!this.state.visitedScenes.includes(sceneId)) this.state.visitedScenes.push(sceneId);
    this._initStageForScene(sceneId);
    const scene = this.project.scenes.find(s => s.id === sceneId);
    if (scene) {
      if (scene.backgroundImageUrl) this._loadImage(scene.backgroundImageUrl);
      scene.objects.forEach(o => {
        if (o.imageUrl) this._loadImage(o.imageUrl);
        if (o.spriteSheetId) { const sh=this.project.spriteSheets?.find(s=>s.id===o.spriteSheetId); if(sh?.imageUrl) this._loadImage(sh.imageUrl); }
      });
      const mc = this.project.mainCharacter;
      if (mc) {
        ['up','down','left','right'].forEach(dir => {
          const sh = this._getCharSheet(dir); if (sh?.imageUrl) this._loadImage(sh.imageUrl);
        });
      }
      for(const npc of (this.project.npcs||[])){
        ['up','down','left','right'].forEach(dir=>{
          const a=npc.animations[dir]; if(a?.spriteSheetId){
            const sh=this.project.spriteSheets?.find(s=>s.id===a.spriteSheetId); if(sh?.imageUrl) this._loadImage(sh.imageUrl);
          }
        });
      }
      // Resolve spawn: entryOverride → characterPlacement (stage start only) → null
      if(entryOverride&&mc){
        const facing=entryOverride.facing||mc.defaultFacing||'down';
        this.state.character={x:entryOverride.x,y:entryOverride.y,waypoints:[],waypointIndex:0,facing,moving:false,animFrame:this._getAnimStartFrame(facing),animTimer:0,scale:1,targetScale:1,speedMult:1,targetSpeedMult:1};
      } else if(stageStart) {
        const cp=scene.characterPlacement;
        if(cp?.visible&&mc){
          const facing=cp.facing||mc.defaultFacing||'down';
          this.state.character={x:cp.x,y:cp.y,waypoints:[],waypointIndex:0,facing,moving:false,animFrame:this._getAnimStartFrame(facing),animTimer:0,scale:1,targetScale:1,speedMult:1,targetSpeedMult:1};
        } else { this.state.character=null; }
      } else {
        this.state.character=null;
      }
      // Pre-seed activeHotspots so spawn-position hotspots don't fire 'enter' immediately
      if(this.state.character&&mc){
        const sfx=this.state.character.x+mc.width/2,sfy=this.state.character.y+mc.height;
        for(const obj of scene.objects){
          if(obj.type!=='hotspot') continue;
          if(sfx>=obj.x&&sfx<=obj.x+obj.width&&sfy>=obj.y&&sfy<=obj.y+obj.height) this.state.activeHotspots.add(obj.id);
        }
      }
      // Pre-seed activeTeleportZones so spawn-position teleport zones don't fire immediately
      if(this.state.character&&mc){
        const sfx=this.state.character.x+mc.width/2,sfy=this.state.character.y+mc.height;
        for(const zone of (scene.teleportZones||[])){
          if(sfx>=zone.x&&sfx<=zone.x+zone.width&&sfy>=zone.y&&sfy<=zone.y+zone.height) this.state.activeTeleportZones.add(zone.id);
        }
      }
      // Initialize NPC movement states
      const npcStateMap=new Map();
      (scene.objects||[]).filter(o=>o.type==='character'&&o.npcId&&o.movementInstruction&&o.movementInstruction!=='none').forEach(o=>{
        const npc=(this.project.npcs||[]).find(n=>n.id===o.npcId);
        npcStateMap.set(o.id,{x:o.x,y:o.y,facing:npc?.defaultFacing||'down',animFrame:0,animTimer:0,waypoints:[],waypointIndex:0,behaviorTimer:0,behaviorPhase:'idle',attackFired:false,scale:1});
      });
      this.state.npcStates=npcStateMap;
    }
    const hotspotIds=new Set(scene?.objects.filter(o=>o.type==='hotspot').map(o=>o.id)??[]);
    this.project.events
      .filter(e=>e.sceneId===sceneId&&this._evTriggers(e).includes('enter')&&e.enabled&&!hotspotIds.has(e.objectId))
      .forEach(ev=>this._execEvent(ev));
  }

  _loop() {
    if (!this.state.running) return;
    const now = performance.now();
    const dt = this.lastFrameTime ? Math.min(now - this.lastFrameTime, 100) : 16;
    this.lastFrameTime = now;
    if(!this.state.showTitleScreen){
      this._updateCharacter(dt);
      const scene=this.project.scenes.find(s=>s.id===this.state.currentSceneId);
      if(scene){this._updateArrowMovement(dt,scene);this._checkHotspots(scene);this._checkCollisions(scene);this._checkScaleZones(scene);this._checkSceneEdges(scene);this._checkTeleportZones(scene);this._updateNpcs(dt,scene);}
      if(this.state.cinematic) this._updateCinematic(dt);
    }
    this._render();
    this.frameId = requestAnimationFrame(() => this._loop());
  }

  _evTriggers(ev){return [ev.trigger,...(ev.triggers||[])];}

  _checkCollisions(scene){
    const char=this.state.character,mc=this.project.mainCharacter;
    if(!char||!mc) return;
    const scale=char.scale??1;
    const hx=char.x,hy=char.y,hw=mc.width*scale,hh=mc.height*scale;
    const sceneIdAtEntry=this.state.currentSceneId;
    const nowColliding=new Set();
    for(const obj of scene.objects){
      if(this.state.currentSceneId!==sceneIdAtEntry) break;
      const vis=this.objectVisibility.has(obj.id)?this.objectVisibility.get(obj.id):obj.visible;
      if(!vis||this.removedObjects.has(obj.id)) continue;
      const ns=this.state.npcStates.get(obj.id);
      const ox=ns?ns.x:obj.x,oy=ns?ns.y:obj.y;
      const overlaps=hx<ox+obj.width&&hx+hw>ox&&hy<oy+obj.height&&hy+hh>oy;
      if(!overlaps) continue;
      nowColliding.add(obj.id);
      if(!this.activeCollisions.has(obj.id)){
        this.project.events.filter(e=>e.sceneId===scene.id&&e.objectId===obj.id&&this._evTriggers(e).includes('collision')&&e.enabled)
          .forEach(ev=>this._execEvent(ev));
      }
    }
    this.activeCollisions.forEach(id=>{if(!nowColliding.has(id))this.activeCollisions.delete(id);});
    nowColliding.forEach(id=>this.activeCollisions.add(id));
  }

  _checkHotspots(scene) {
    const char=this.state.character,mc=this.project.mainCharacter;
    if(!char||!mc) return;
    const fx=char.x+mc.width/2, fy=char.y+mc.height;
    const sceneIdAtEntry=this.state.currentSceneId;
    for(const obj of scene.objects){
      if(this.state.currentSceneId!==sceneIdAtEntry) break;
      if(obj.type!=='hotspot') continue;
      const vis=this.objectVisibility.has(obj.id)?this.objectVisibility.get(obj.id):obj.visible;
      if(!vis||this.removedObjects.has(obj.id)) continue;
      const inside=fx>=obj.x&&fx<=obj.x+obj.width&&fy>=obj.y&&fy<=obj.y+obj.height;
      const wasInside=this.state.activeHotspots.has(obj.id);
      if(inside&&!wasInside){
        this.state.activeHotspots.add(obj.id);
        this.project.events.filter(e=>e.sceneId===scene.id&&e.objectId===obj.id&&this._evTriggers(e).includes('enter')&&e.enabled)
          .forEach(ev=>this._execEvent(ev));
      } else if(!inside&&wasInside){
        this.state.activeHotspots.delete(obj.id);
        this.project.events.filter(e=>e.sceneId===scene.id&&e.objectId===obj.id&&this._evTriggers(e).includes('exit')&&e.enabled)
          .forEach(ev=>this._execEvent(ev));
      }
    }
  }

  _checkScaleZones(scene) {
    const char=this.state.character,mc=this.project.mainCharacter;
    if(!char||!mc) return;
    const fx=char.x+mc.width/2, fy=char.y+mc.height;
    let ts=1,tm=1;
    for(const z of (scene.scaleZones||[])){
      if(fx>=z.x&&fx<=z.x+z.width&&fy>=z.y&&fy<=z.y+z.height){ts=z.scale;tm=z.speedMultiplier;break;}
    }
    char.targetScale=ts; char.targetSpeedMult=tm;
  }

  _checkTeleportZones(scene) {
    const char=this.state.character,mc=this.project.mainCharacter;
    if(!char||!mc) return;
    const fx=char.x+mc.width/2,fy=char.y+mc.height;
    for(const zone of (scene.teleportZones||[])){
      const inside=fx>=zone.x&&fx<=zone.x+zone.width&&fy>=zone.y&&fy<=zone.y+zone.height;
      const wasInside=this.state.activeTeleportZones.has(zone.id);
      if(inside&&!wasInside){
        this.state.activeTeleportZones.add(zone.id);
        if(zone.linkedSceneId&&zone.linkedZoneId){
          const tScene=this.project.scenes.find(s=>s.id===zone.linkedSceneId);
          const tZone=tScene?(tScene.teleportZones||[]).find(z=>z.id===zone.linkedZoneId):null;
          if(tScene&&tZone){
            const ax=Math.max(0,Math.min(tScene.width-mc.width,tZone.x+tZone.width/2-mc.width/2));
            const ay=Math.max(0,Math.min(tScene.height-mc.height,tZone.y+tZone.height/2-mc.height/2));
            const facing=zone.entryFacing||char.facing;
            this._loadScene(tScene.id,{x:ax,y:ay,facing});
            return;
          }
        }
      } else if(!inside&&wasInside){
        this.state.activeTeleportZones.delete(zone.id);
      }
    }
  }
  _findSafeArrival(scene,mc,nomX,nomY,side) {
    const zones=scene.blockedZones||[];
    const overlaps=(x,y)=>{
      for(const z of zones){
        if(x<z.x+z.width&&x+mc.width>z.x&&y<z.y+z.height&&y+mc.height>z.y) return true;
      }
      return false;
    };
    if(!overlaps(nomX,nomY)) return {x:nomX,y:nomY};
    const step=4;
    if(side==='left'||side==='right'){
      const maxScan=scene.height;
      for(let d=step;d<=maxScan;d+=step){
        for(const cy of [nomY+d,nomY-d]){
          const c=Math.max(0,Math.min(scene.height-mc.height,cy));
          if(!overlaps(nomX,c)) return {x:nomX,y:c};
        }
      }
    } else {
      const maxScan=scene.width;
      for(let d=step;d<=maxScan;d+=step){
        for(const cx of [nomX+d,nomX-d]){
          const c=Math.max(0,Math.min(scene.width-mc.width,cx));
          if(!overlaps(c,nomY)) return {x:c,y:nomY};
        }
      }
    }
    return {x:nomX,y:nomY};
  }
  _checkSceneEdges(scene) {
    const char=this.state.character,mc=this.project.mainCharacter;
    if(!char||!mc) return;
    if(!scene.exits||scene.exits.length===0) return;
    let side=null;
    if(char.x<=0) side='left';
    else if(char.x+mc.width>=scene.width) side='right';
    else if(char.y<=0) side='top';
    else if(char.y+mc.height>=scene.height) side='bottom';
    if(!side) return;
    const exitDef=scene.exits.find(e=>e.side===side);
    if(!exitDef) return;
    const targetScene=this.project.scenes.find(s=>s.id===exitDef.targetSceneId);
    if(!targetScene) return;
    const sceneIdAtEntry=this.state.currentSceneId;
    const clampedY=Math.max(0,Math.min(targetScene.height-mc.height,char.y));
    const clampedX=Math.max(0,Math.min(targetScene.width-mc.width,char.x));
    let nomX,nomY;
    if(side==='right'){nomX=40;nomY=clampedY;}
    else if(side==='left'){nomX=targetScene.width-40-mc.width;nomY=clampedY;}
    else if(side==='top'){nomX=clampedX;nomY=targetScene.height-40-mc.height;}
    else{nomX=clampedX;nomY=40;}
    const safe=this._findSafeArrival(targetScene,mc,nomX,nomY,side);
    const inferredFacing=side==='right'?'right':side==='left'?'left':side==='top'?'up':'down';
    const facing=exitDef.entryFacing||inferredFacing;
    if(this.state.currentSceneId!==sceneIdAtEntry) return;
    this._loadScene(targetScene.id,{x:safe.x,y:safe.y,facing});
  }

  _updateCharacter(dt) {
    const char = this.state.character, mc = this.project.mainCharacter;
    if (!char || !mc) return;
    const lf=Math.min(1,dt*3/1000);
    char.scale+=(char.targetScale-char.scale)*lf;
    char.speedMult+=(char.targetSpeedMult-char.speedMult)*lf;
    if (!char.moving) return;
    const target = char.waypoints[char.waypointIndex];
    if (!target) { char.moving = false; return; }
    const tx = target.x - mc.width/2, ty = target.y - mc.height/2;
    const dx = tx - char.x, dy = ty - char.y;
    const dist = Math.sqrt(dx*dx + dy*dy);
    if (dist < 3) {
      char.x = tx; char.y = ty; char.waypointIndex++;
      if (char.waypointIndex >= char.waypoints.length) {
        char.moving = false; char.animFrame = this._getAnimStartFrame(char.facing); char.animTimer = 0;
      }
      return;
    }
    if (Math.abs(dx) >= Math.abs(dy)) { char.facing = dx>0?'right':'left'; }
    else { char.facing = dy>0?'down':'up'; }
    const step = CHAR_SPEED*char.speedMult*(dt/1000), ratio = Math.min(step/dist,1);
    char.x += dx*ratio; char.y += dy*ratio;
    const anim = this._getCharAnim(char.facing);
    if (anim && anim.fps > 0) {
      const fms = 1000/anim.fps; char.animTimer += dt;
      while (char.animTimer >= fms) {
        char.animTimer -= fms; char.animFrame++;
        if (char.animFrame > anim.endFrame) char.animFrame = anim.startFrame;
      }
    }
  }

  _isBlockedAt(x,y,cw,ch,scene){
    for(const z of (scene.blockedZones||[])){
      if(x<z.x+z.width&&x+cw>z.x&&y<z.y+z.height&&y+ch>z.y) return true;
    }
    return false;
  }

  _updateArrowMovement(dt,scene){
    const char=this.state.character,mc=this.project.mainCharacter;
    if(!char||!mc) return;
    if(this.state.dialogText||this.state.cinematic||this.state.miniGame||this.state.questLogOpen) return;
    const moveX=(this.activeKeys.has('ArrowRight')?1:0)-(this.activeKeys.has('ArrowLeft')?1:0);
    const moveY=(this.activeKeys.has('ArrowDown')?1:0)-(this.activeKeys.has('ArrowUp')?1:0);
    if(moveX===0&&moveY===0) return;
    if(char.waypoints.length>0){char.waypoints=[];char.waypointIndex=0;char.moving=false;}
    const len=Math.sqrt(moveX*moveX+moveY*moveY);
    const speed=CHAR_SPEED*char.speedMult;
    const dx=(moveX/len)*speed*dt/1000;
    const dy=(moveY/len)*speed*dt/1000;
    if(Math.abs(moveX)>=Math.abs(moveY)) char.facing=moveX>0?'right':'left';
    else char.facing=moveY>0?'down':'up';
    const cw=mc.width*char.scale,ch=mc.height*char.scale;
    const newX=Math.max(0,Math.min(scene.width-cw,char.x+dx));
    if(!this._isBlockedAt(newX,char.y,cw,ch,scene)) char.x=newX;
    const newY=Math.max(0,Math.min(scene.height-ch,char.y+dy));
    if(!this._isBlockedAt(char.x,newY,cw,ch,scene)) char.y=newY;
    char.moving=true;
    const anim=this._getCharAnim(char.facing);
    if(anim&&anim.fps>0){
      const fms=1000/anim.fps; char.animTimer+=dt;
      while(char.animTimer>=fms){char.animTimer-=fms;char.animFrame++;if(char.animFrame>anim.endFrame)char.animFrame=anim.startFrame;}
    }
  }

  _render() {
    const { canvas, ctx } = this;
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    if(this.state.showTitleScreen){ this._renderTitleScreen(); return; }
    const scene = this.project.scenes.find(s => s.id === this.state.currentSceneId);
    if (!scene) {
      ctx.fillStyle = '#1a1a2e'; ctx.fillRect(0,0,canvas.width,canvas.height);
      ctx.fillStyle = '#e2e8f0'; ctx.font = '20px sans-serif';
      ctx.textAlign = 'center'; ctx.textBaseline = 'middle';
      ctx.fillText('No scene', canvas.width/2, canvas.height/2);
      return;
    }
    const sx = canvas.width/scene.width, sy = canvas.height/scene.height;
    ctx.save(); ctx.scale(sx, sy);
    ctx.fillStyle = scene.backgroundColor || '#000';
    ctx.fillRect(0, 0, scene.width, scene.height);
    if (scene.backgroundImageUrl) {
      const img = this.imageCache.get(scene.backgroundImageUrl);
      if (img) ctx.drawImage(img, 0, 0, scene.width, scene.height);
    }
    const sortedObjs=[...scene.objects].sort((a,b)=>a.zIndex-b.zIndex);
    const char=this.state.character,mc=this.project.mainCharacter;
    const charDepth=(char&&mc)?char.y+mc.height:null;
    let charDrawn=false;
    for(const obj of sortedObjs){
      const vis=this.objectVisibility.has(obj.id)?this.objectVisibility.get(obj.id):obj.visible;
      if(!vis||this.removedObjects.has(obj.id)) continue;
      if(!charDrawn&&charDepth!==null&&obj.zIndex>charDepth){this._renderCharacter();charDrawn=true;}
      let ro=obj;
      const _ns=(obj.type==='character'&&obj.npcId&&!this.state.cinematic)?this.state.npcStates.get(obj.id):null;
      const _ov=obj.type==='character'&&obj.npcId&&this.state.cinematic?this.state.cinematic.npcOverrides.get(obj.npcId):null;
      if(_ov) ro=Object.assign({},obj,{x:_ov.x,y:_ov.y});
      else if(_ns) ro=Object.assign({},obj,{x:_ns.x,y:_ns.y});
      const _npcScale=(ro.type==='character'&&_ns)?(_ns.scale??1):1;
      const _npcSW=ro.width*_npcScale,_npcSH=ro.height*_npcScale;
      const _npcRX=Math.round(ro.x+(ro.width-_npcSW)/2),_npcRY=Math.round(ro.y+ro.height-_npcSH);
      ctx.save(); ctx.globalAlpha=ro.opacity;
      const ssSheet=ro.spriteSheetId?this.project.spriteSheets?.find(s=>s.id===ro.spriteSheetId):null;
      const ssImg=ssSheet?this.imageCache.get(ssSheet.imageUrl):null;
      if(ssImg&&ssSheet){
        const fi=ro.frameIndex??0,col=fi%ssSheet.cols,row=Math.floor(fi/ssSheet.cols);
        ctx.drawImage(ssImg,col*ssSheet.frameWidth,row*ssSheet.frameHeight,ssSheet.frameWidth,ssSheet.frameHeight,_npcRX,_npcRY,_npcSW,_npcSH);
        ctx.restore(); continue;
      }
      if(ro.type==='character'&&ro.npcId){
        const npc=(this.project.npcs||[]).find(n=>n.id===ro.npcId);
        if(npc){
          const facing=(_ns&&_ns.behaviorPhase==='moving')?_ns.facing:npc.defaultFacing;
          const fa=npc.animations[facing]||npc.animations[npc.defaultFacing];
          if(fa?.spriteSheetId){
            const nsh=this.project.spriteSheets?.find(s=>s.id===fa.spriteSheetId);
            if(nsh){
              const nim=this.imageCache.get(nsh.imageUrl);
              if(nim){
                const adef=nsh.animations.find(a=>a.id===fa.animationId);
                const fi=(_ns&&_ns.behaviorPhase==='moving')?_ns.animFrame:(adef?.startFrame??0);
                const col=fi%nsh.cols,row=Math.floor(fi/nsh.cols);
                ctx.drawImage(nim,col*nsh.frameWidth,row*nsh.frameHeight,nsh.frameWidth,nsh.frameHeight,_npcRX,_npcRY,_npcSW,_npcSH);
                ctx.restore(); continue;
              }
            }
          }
        }
      }
      const img=ro.imageUrl?this.imageCache.get(ro.imageUrl):null;
      if(img){
        ctx.drawImage(img,ro.x,ro.y,ro.width,ro.height);
      } else {
        const colors={sprite:'#4f46e5',character:'#7c3aed',item:'#d97706',hotspot:'rgba(99,102,241,0.15)',background:'#1e293b',terrain:'#14532d'};
        ctx.fillStyle=colors[ro.type]||'#4f46e5';
        ctx.fillRect(_npcRX,_npcRY,_npcSW,_npcSH);
        if(ro.type!=='hotspot'){
          ctx.fillStyle='#fff'; ctx.font='14px sans-serif';
          ctx.textAlign='center'; ctx.textBaseline='middle';
          ctx.fillText(ro.name,_npcRX+_npcSW/2,_npcRY+_npcSH/2);
        }
      }
      ctx.restore();
    }
    if(!charDrawn) this._renderCharacter();
    ctx.restore();
    if (this.state.dialogText) this._renderDialog();
    if(this.state.cinematic&&this.state.cinematic.actionText) this._renderActionLabel();
    this._renderQuestHUDButton();
    if(this.state.questLogOpen) this._renderQuestLog();
  }

  _renderTitleScreen(){
    const{canvas,ctx}=this,ts=this.project.titleScreen;
    ctx.fillStyle=ts?.backgroundColor||'#000000';
    ctx.fillRect(0,0,canvas.width,canvas.height);
    if(ts?.backgroundImageUrl){const img=this.imageCache.get(ts.backgroundImageUrl);if(img)ctx.drawImage(img,0,0,canvas.width,canvas.height);}
    if(ts?.titleText){
      ctx.font='bold '+(ts.titleFontSize||48)+'px sans-serif';
      ctx.fillStyle=ts.titleColor||'#ffffff';
      ctx.textAlign='center';ctx.textBaseline='middle';
      ctx.fillText(ts.titleText,canvas.width/2,canvas.height*0.22);
    }
    if(ts?.subtitleText){
      ctx.font=(ts.subtitleFontSize||24)+'px sans-serif';
      ctx.fillStyle=ts.subtitleColor||'#cccccc';
      ctx.textAlign='center';ctx.textBaseline='middle';
      ctx.fillText(ts.subtitleText,canvas.width/2,canvas.height*0.36);
    }
    this.titleScreenButtonRects=[];
    const btns=[...(ts?.buttons||[])].sort((a,b)=>a.order-b.order);
    const bw=Math.min(240,canvas.width*0.5),bh=48,bg=16,sy=canvas.height*0.52;
    btns.forEach((btn,i)=>{
      const x=(canvas.width-bw)/2,y=sy+i*(bh+bg);
      this.titleScreenButtonRects.push({id:btn.id,action:btn.action,x,y,w:bw,h:bh});
      ctx.fillStyle='rgba(99,102,241,0.9)';
      ctx.beginPath();ctx.roundRect(x,y,bw,bh,8);ctx.fill();
      ctx.strokeStyle='#818cf8';ctx.lineWidth=2;ctx.stroke();
      ctx.fillStyle='#ffffff';ctx.font='bold 16px sans-serif';
      ctx.textAlign='center';ctx.textBaseline='middle';
      ctx.fillText(btn.label,x+bw/2,y+bh/2);
    });
  }

  _startGame(_action){
    this.state.showTitleScreen=false;
    this._loadScene(this.state.currentSceneId,undefined,true);
  }

  _updateNpcs(dt,scene){
    const NPC_SPEEDS={'none':0,'roam-slow-and-eat-grass':50,'roam-human-in-field':120,'follow-hero':150,'follow-and-attack-hero':180};
    for(const obj of scene.objects){
      if(obj.type!=='character'||!obj.npcId) continue;
      const instr=obj.movementInstruction||'none';
      if(instr==='none') continue;
      const ns=this.state.npcStates.get(obj.id);
      if(!ns) continue;
      const npc=(this.project.npcs||[]).find(n=>n.id===obj.npcId);
      if(!npc) continue;
      const speed=NPC_SPEEDS[instr]||0;
      // Compute NPC scale from scale zones
      const npcFX=ns.x+obj.width/2,npcFY=ns.y+obj.height;
      let npcScale=1;
      for(const z of (scene.scaleZones||[])){if(npcFX>=z.x&&npcFX<=z.x+z.width&&npcFY>=z.y&&npcFY<=z.y+z.height){npcScale=z.scale;break;}}
      ns.scale=npcScale;
      const snW=obj.width*npcScale,snH=obj.height*npcScale;
      ns.behaviorTimer=Math.max(0,ns.behaviorTimer-dt);
      if(ns.behaviorPhase==='idle'&&ns.behaviorTimer<=0){
        if(instr==='roam-slow-and-eat-grass'){
          const angle=Math.random()*Math.PI*2,dist=80+Math.random()*120;
          const tx=Math.max(0,Math.min(scene.width-obj.width,ns.x+Math.cos(angle)*dist));
          const ty=Math.max(0,Math.min(scene.height-obj.height,ns.y+Math.sin(angle)*dist));
          ns.waypoints=findPath(scene.blockedZones||[],scene.width,scene.height,ns.x+obj.width/2,ns.y+obj.height,tx+obj.width/2,ty+obj.height,snW,snH);
          ns.waypointIndex=0;ns.behaviorPhase=ns.waypoints.length>0?'moving':'idle';
          if(ns.behaviorPhase==='idle') ns.behaviorTimer=2000+Math.random()*4000;
        } else if(instr==='roam-human-in-field'){
          const tx=Math.random()*(scene.width-obj.width);
          const ty=Math.random()*(scene.height-obj.height);
          ns.waypoints=findPath(scene.blockedZones||[],scene.width,scene.height,ns.x+obj.width/2,ns.y+obj.height,tx+obj.width/2,ty+obj.height,snW,snH);
          ns.waypointIndex=0;ns.behaviorPhase=ns.waypoints.length>0?'moving':'idle';
          if(ns.behaviorPhase==='idle') ns.behaviorTimer=1000+Math.random()*2000;
        } else if(instr==='follow-hero'||instr==='follow-and-attack-hero'){
          const char=this.state.character,mc=this.project.mainCharacter;
          if(char&&mc){
            const stopGap=instr==='follow-and-attack-hero'?40:80;
            const dx=ns.x-char.x,dy=ns.y-char.y,dist=Math.sqrt(dx*dx+dy*dy);
            if(dist>stopGap){
              ns.waypoints=findPath(scene.blockedZones||[],scene.width,scene.height,ns.x+obj.width/2,ns.y+obj.height,char.x+mc.width/2,char.y+mc.height,snW,snH);
              ns.waypointIndex=0;ns.behaviorPhase=ns.waypoints.length>0?'moving':'idle';
            } else {
              if(instr==='follow-and-attack-hero'&&!ns.attackFired){
                ns.attackFired=true;this.state.variables['npc_attacked_'+obj.id]=true;
                if(!this.state.dialogText) this.state.dialogText=(npc.name||'NPC')+' attacks you!';
              }
              ns.behaviorTimer=2000;
            }
          } else {ns.behaviorTimer=2000;}
        }
      }
      if(ns.behaviorPhase==='moving'){
        const target=ns.waypoints[ns.waypointIndex];
        if(!target){
          ns.behaviorPhase='idle';
          ns.behaviorTimer=instr==='roam-slow-and-eat-grass'?3000+Math.random()*5000:instr==='roam-human-in-field'?1000+Math.random()*2000:1500+Math.random()*1000;
        } else {
          const tx=target.x-obj.width/2,ty=target.y-obj.height;
          const dx=tx-ns.x,dy=ty-ns.y,dist=Math.sqrt(dx*dx+dy*dy);
          if(dist<3){ns.x=tx;ns.y=ty;ns.waypointIndex++;}
          else {
            if(Math.abs(dx)>=Math.abs(dy)){ns.facing=dx>0?'right':'left';}else{ns.facing=dy>0?'down':'up';}
            const step=speed*(dt/1000),ratio=Math.min(step/dist,1);
            ns.x+=dx*ratio;ns.y+=dy*ratio;
            const ac=npc.animations[ns.facing];
            if(ac?.spriteSheetId){
              const sh=this.project.spriteSheets?.find(s=>s.id===ac.spriteSheetId);
              const ad=sh?.animations.find(a=>a.id===ac.animationId);
              if(ad&&ad.fps>0){const fms=1000/ad.fps;ns.animTimer+=dt;while(ns.animTimer>=fms){ns.animTimer-=fms;ns.animFrame++;if(ns.animFrame>ad.endFrame)ns.animFrame=ad.startFrame;}}
            }
          }
        }
      }
      if(instr==='follow-and-attack-hero'&&!ns.attackFired){
        const char=this.state.character,mc=this.project.mainCharacter;
        if(char&&mc){const dx=ns.x-char.x,dy=ns.y-char.y;if(Math.sqrt(dx*dx+dy*dy)<=40){ns.attackFired=true;this.state.variables['npc_attacked_'+obj.id]=true;if(!this.state.dialogText) this.state.dialogText=(npc.name||'NPC')+' attacks you!';}}
      }
    }
  }

  _renderCharacter() {
    const char=this.state.character, mc=this.project.mainCharacter;
    if (!char||!mc) return;
    const {ctx}=this, cw=mc.width, ch=mc.height;
    const scale=char.scale??1;
    const sw=cw*scale, sh=ch*scale;
    const rx=Math.round(char.x+(cw-sw)/2), ry=Math.round(char.y+ch-sh);
    const sheet=this._getCharSheet(char.facing);
    const img=sheet?this.imageCache.get(sheet.imageUrl):null;
    if (img&&sheet) {
      const col=char.animFrame%sheet.cols, row=Math.floor(char.animFrame/sheet.cols);
      ctx.drawImage(img,col*sheet.frameWidth,row*sheet.frameHeight,sheet.frameWidth,sheet.frameHeight,rx,ry,sw,sh);
    } else {
      ctx.save();
      ctx.fillStyle='rgba(99,102,241,0.7)';
      ctx.fillRect(rx,ry,sw,sh);
      ctx.fillStyle='#fff'; ctx.font=Math.min(12,sh*0.18)+'px sans-serif';
      ctx.textAlign='center'; ctx.textBaseline='middle';
      ctx.fillText(mc.name||'Player',rx+sw/2,ry+sh/2);
      ctx.restore();
    }
  }

  _renderDialog() {
    const {canvas,ctx}=this;
    const pad=24,bh=130,by=canvas.height-bh-12;
    ctx.fillStyle='rgba(0,0,0,0.88)'; ctx.fillRect(8,by,canvas.width-16,bh);
    ctx.strokeStyle='#6366f1'; ctx.lineWidth=2; ctx.strokeRect(8,by,canvas.width-16,bh);
    const fs=Math.max(12,Math.min(16,canvas.width/50));
    ctx.font=fs+'px sans-serif'; ctx.fillStyle='#e2e8f0';
    ctx.textAlign='left'; ctx.textBaseline='top';
    const mw=canvas.width-16-pad*2, lh=fs+6;
    let ly=by+pad;
    const paragraphs=(this.state.dialogText||'').split('\\n');
    paragraphs.forEach(para=>{
      const words=para.split(' '); let line='';
      words.forEach(w=>{
        const t=line+w+' ';
        if(ctx.measureText(t).width>mw&&line){ctx.fillText(line.trim(),8+pad,ly);line=w+' ';ly+=lh;}
        else line=t;
      });
      if(line.trim()){ctx.fillText(line.trim(),8+pad,ly);ly+=lh;}
    });
    ctx.fillStyle='#6366f1'; ctx.font='12px sans-serif'; ctx.textAlign='right'; ctx.textBaseline='bottom';
    ctx.fillText('\\u25b6 Click to continue',canvas.width-16,by+bh-8);
  }

  _renderQuestHUDButton() {
    if(this.state.showTitleScreen) return;
    const {ctx,canvas}=this;
    const w=52,h=28,x=canvas.width-w-8,y=8;
    this.questButtonRect={x,y,w,h};
    ctx.fillStyle='rgba(0,0,0,0.75)'; ctx.strokeStyle='#4f46e5'; ctx.lineWidth=1.5;
    ctx.beginPath(); ctx.roundRect(x,y,w,h,6); ctx.fill(); ctx.stroke();
    ctx.fillStyle='#e2e8f0';
    ctx.font='bold '+Math.max(10,Math.min(12,canvas.width/80))+'px sans-serif';
    ctx.textAlign='center'; ctx.textBaseline='middle';
    ctx.fillText('\u{1F4DC} '+this.state.activeQuestIds.length,x+w/2,y+h/2);
  }

  _renderQuestLog() {
    const {ctx,canvas}=this;
    const pw=Math.min(320,canvas.width*0.85),ph=Math.min(canvas.height*0.78,500);
    const px=canvas.width-pw-8,py=44;
    ctx.fillStyle='rgba(15,15,30,0.96)'; ctx.strokeStyle='#4f46e5'; ctx.lineWidth=2;
    ctx.beginPath(); ctx.roundRect(px,py,pw,ph,8); ctx.fill(); ctx.stroke();
    const fs=Math.max(11,Math.min(13,canvas.width/70)),lh=fs+6,pad=14;
    ctx.fillStyle='#e2e8f0'; ctx.font='bold '+(fs+2)+'px sans-serif';
    ctx.textAlign='left'; ctx.textBaseline='top';
    ctx.fillText('Quest Log',px+pad,py+pad);
    const cw=22,ch=22,cx2=px+pw-cw-8,cy2=py+8;
    this.questLogCloseRect={x:cx2,y:cy2,w:cw,h:ch};
    ctx.fillStyle='#374151'; ctx.beginPath(); ctx.roundRect(cx2,cy2,cw,ch,4); ctx.fill();
    ctx.fillStyle='#9ca3af'; ctx.font='bold '+fs+'px sans-serif'; ctx.textAlign='center'; ctx.textBaseline='middle';
    ctx.fillText('x',cx2+cw/2,cy2+ch/2);
    const quests=this.project.quests||[];
    let curY=py+pad+fs+4+lh;
    const wrapText=(text,x,mw,startY)=>{
      ctx.font=fs+'px sans-serif'; ctx.textAlign='left'; ctx.textBaseline='top';
      const words=text.split(' '); let line='',y=startY;
      for(const word of words){
        const t=line+word+' ';
        if(ctx.measureText(t).width>mw&&line){ctx.fillText(line.trim(),x,y);line=word+' ';y+=lh;}else{line=t;}
      }
      if(line.trim()){ctx.fillText(line.trim(),x,y);y+=lh;} return y;
    };
    const active=this.state.activeQuestIds.map(id=>quests.find(q=>q.id===id)).filter(Boolean);
    if(active.length>0){
      ctx.fillStyle='#818cf8'; ctx.font='bold '+fs+'px sans-serif'; ctx.textAlign='left'; ctx.textBaseline='top';
      ctx.fillText('Active',px+pad,curY); curY+=lh+2;
      for(const quest of active){
        if(curY>py+ph-pad) break;
        ctx.fillStyle='#e2e8f0'; ctx.font='bold '+fs+'px sans-serif'; ctx.textAlign='left'; ctx.textBaseline='top';
        ctx.fillText(quest.name,px+pad,curY); curY+=lh;
        ctx.fillStyle='#94a3b8';
        curY=wrapText(quest.description,px+pad,pw-pad*2,curY);
        for(const obj of quest.objectives||[]){
          if(curY>py+ph-pad) break;
          ctx.fillStyle='#6b7280'; ctx.font=fs+'px sans-serif'; ctx.textAlign='left'; ctx.textBaseline='top';
          ctx.fillText('  o '+obj.text,px+pad+4,curY); curY+=lh;
        }
        curY+=4;
      }
    }
    const completed=this.state.completedQuestIds.map(id=>quests.find(q=>q.id===id)).filter(Boolean);
    if(completed.length>0&&curY<py+ph-pad){
      ctx.fillStyle='#6b7280'; ctx.font='bold '+fs+'px sans-serif'; ctx.textAlign='left'; ctx.textBaseline='top';
      ctx.fillText('Completed',px+pad,curY); curY+=lh+2;
      for(const quest of completed){
        if(curY>py+ph-pad) break;
        ctx.fillStyle='#4b5563'; ctx.font=fs+'px sans-serif'; ctx.textAlign='left'; ctx.textBaseline='top';
        ctx.fillText('✓ '+quest.name,px+pad,curY); curY+=lh;
      }
    }
    if(active.length===0&&completed.length===0){
      ctx.fillStyle='#6b7280'; ctx.font=fs+'px sans-serif'; ctx.textAlign='left'; ctx.textBaseline='top';
      ctx.fillText('No quests yet.',px+pad,curY);
    }
  }

  _handleKeyDown(e) {
    if(this.state.showTitleScreen||this.state.miniGame) return;
    if(e.key==='j'||e.key==='J') this.state.questLogOpen=!this.state.questLogOpen;
    this.activeKeys.add(e.key);
  }

  _handleKeyUp(e) {
    this.activeKeys.delete(e.key);
  }

  _scenePos(e) {
    const r=this.canvas.getBoundingClientRect();
    const cx=(e.clientX-r.left)*(this.canvas.width/r.width);
    const cy=(e.clientY-r.top)*(this.canvas.height/r.height);
    const scene=this.project.scenes.find(s=>s.id===this.state.currentSceneId);
    if (!scene) return {x:cx,y:cy};
    return {x:cx/(this.canvas.width/scene.width), y:cy/(this.canvas.height/scene.height)};
  }

  _handleClick(e) {
    if(this.state.showTitleScreen){
      const r=this.canvas.getBoundingClientRect();
      const cx=(e.clientX-r.left)*(this.canvas.width/r.width);
      const cy=(e.clientY-r.top)*(this.canvas.height/r.height);
      for(const br of this.titleScreenButtonRects){
        if(cx>=br.x&&cx<=br.x+br.w&&cy>=br.y&&cy<=br.y+br.h){this._startGame(br.action);return;}
      }
      return;
    }
    if (this.state.dialogText) {
      this.state.dialogText=null;
      const cb=this.state.dialogCallback; this.state.dialogCallback=null; if(cb)cb();
      return;
    }
    const r2=this.canvas.getBoundingClientRect();
    const cx2=(e.clientX-r2.left)*(this.canvas.width/r2.width);
    const cy2=(e.clientY-r2.top)*(this.canvas.height/r2.height);
    if(this.state.questLogOpen){
      const cl=this.questLogCloseRect;
      if(cx2>=cl.x&&cx2<=cl.x+cl.w&&cy2>=cl.y&&cy2<=cl.y+cl.h){this.state.questLogOpen=false;return;}
      return;
    }
    const qb=this.questButtonRect;
    if(cx2>=qb.x&&cx2<=qb.x+qb.w&&cy2>=qb.y&&cy2<=qb.y+qb.h){this.state.questLogOpen=true;return;}
    const pos=this._scenePos(e);
    const scene=this.project.scenes.find(s=>s.id===this.state.currentSceneId);
    if (!scene) return;
    const obj=this._objAt(scene,pos.x,pos.y);
    if (obj) {
      this.project.events
        .filter(ev=>ev.sceneId===scene.id&&ev.objectId===obj.id&&this._evTriggers(ev).includes('click')&&ev.enabled)
        .forEach(ev=>this._execEvent(ev));
      return;
    }
    const char=this.state.character, mc=this.project.mainCharacter;
    if (char&&mc) {
      const path=findPath(scene.blockedZones||[],scene.width,scene.height,
        char.x+mc.width/2, char.y+mc.height/2, pos.x, pos.y, mc.width*(char.scale??1), mc.height*(char.scale??1));
      if (path.length>0) { char.waypoints=path; char.waypointIndex=0; char.moving=true; }
    }
  }

  _handleMouseMove(e) {
    if(this.state.showTitleScreen){
      const r=this.canvas.getBoundingClientRect();
      const cx=(e.clientX-r.left)*(this.canvas.width/r.width);
      const cy=(e.clientY-r.top)*(this.canvas.height/r.height);
      const onBtn=this.titleScreenButtonRects.some(br=>cx>=br.x&&cx<=br.x+br.w&&cy>=br.y&&cy<=br.y+br.h);
      this.canvas.style.cursor=onBtn?'pointer':'default';
      return;
    }
    if (this.state.dialogText) return;
    const pos=this._scenePos(e);
    const scene=this.project.scenes.find(s=>s.id===this.state.currentSceneId);
    if (!scene) return;
    this.canvas.style.cursor=this._objAt(scene,pos.x,pos.y)?'pointer':'default';
  }

  _objAt(scene,x,y) {
    return [...scene.objects]
      .filter(o=>o.type!=='hotspot'&&!this.removedObjects.has(o.id)&&(this.objectVisibility.has(o.id)?this.objectVisibility.get(o.id):o.visible))
      .sort((a,b)=>b.zIndex-a.zIndex)
      .find(o=>x>=o.x&&x<=o.x+o.width&&y>=o.y&&y<=o.y+o.height)||null;
  }

  _checkEventCond(c){
    const raw=this.state.variables[c.variable];
    const v=raw!==undefined?String(raw):'';
    switch(c.operator){
      case 'equals':       return v===c.value;
      case 'not_equals':   return v!==c.value;
      case 'greater_than': return Number(v)>Number(c.value);
      case 'less_than':    return Number(v)<Number(c.value);
      case 'contains':     return v.includes(c.value);
      default:             return false;
    }
  }

  _execEvent(ev){
    for(const br of (ev.branches||[])){
      if(!br.conditions?.length) continue;
      const results=br.conditions.map(c=>this._checkEventCond(c));
      const matched=br.logic==='AND'?results.every(Boolean):results.some(Boolean);
      if(matched){br.actions.forEach(a=>this._execAction(a));return;}
    }
    ev.actions.forEach(a=>this._execAction(a));
  }

  _execAction(action){
    switch(action.type){
      case 'navigate_scene':{
        const s=this.project.scenes.find(sc=>sc.id===action.value||sc.name===action.value);
        if(s){
          const eo=(action.entryX!=null&&action.entryY!=null)?{x:action.entryX,y:action.entryY,facing:action.entryFacing}:undefined;
          this._loadScene(s.id,eo);
        }
        break;
      }
      case 'show_dialog': this.state.dialogText=action.value; break;
      case 'set_variable':{
        this._applyVarExpr(action.value);this._evaluateGoals();
        break;
      }
      case 'show_object': this.objectVisibility.set(action.value,true); break;
      case 'hide_object': this.objectVisibility.set(action.value,false); break;
      case 'remove_object': this.removedObjects.add(action.value); break;
      case 'spawn_object':{
        let tpl;
        for(const s of this.project.scenes){tpl=s.objects.find(o=>o.id===action.value);if(tpl)break;}
        if(!tpl) break;
        const tgtScene=this.project.scenes.find(s=>s.id===(action.spawnSceneId||this.state.currentSceneId));
        if(!tgtScene) break;
        const spawnId='sp-'+Date.now()+'-'+Math.random().toString(36).slice(2,8);
        const spawnX=(action.spawnX!=null)?action.spawnX:tpl.x;
        const spawnY=(action.spawnY!=null)?action.spawnY:tpl.y;
        tgtScene.objects.push(Object.assign({},tpl,{id:spawnId,x:spawnX,y:spawnY,visible:true}));
        break;
      }
      case 'play_sound':{
        const a=this.project.assets?.find(a=>a.id===action.value||a.name===action.value);
        if(a?.url) new Audio(a.url).play().catch(()=>{});
        break;
      }
      case 'play_cinematic': this._playCinematic(action.value); break;
      case 'launch_minigame': this._launchMiniGame(action); break;
      case 'trigger_event':{
        const ev=(this.project.events||[]).find(e=>e.id===action.value);
        if(ev) this._execEvent(ev);
        break;
      }
      case 'add_quest':{
        const quest=(this.project.quests||[]).find(q=>q.id===action.value);
        if(!quest) break;
        if(this.state.activeQuestIds.includes(quest.id)||this.state.completedQuestIds.includes(quest.id)) break;
        this.state.activeQuestIds=[...this.state.activeQuestIds,quest.id];
        this.state.dialogText='New Quest: '+quest.name+'\\n'+quest.description;
        break;
      }
      case 'complete_quest':{
        if(!this.state.activeQuestIds.includes(action.value)) break;
        this.state.activeQuestIds=this.state.activeQuestIds.filter(id=>id!==action.value);
        this.state.completedQuestIds=[...this.state.completedQuestIds,action.value];
        const doneQ=(this.project.quests||[]).find(q=>q.id===action.value);
        if(doneQ) this.state.dialogText='Quest Complete: '+doneQ.name;
        break;
      }
    }
  }

  _playCinematic(cinematicId){
    const cine=(this.project.cinematics||[]).find(c=>c.id===cinematicId);
    if(!cine||cine.steps.length===0) return;
    if(cine.sceneId&&cine.sceneId!==this.state.currentSceneId) this._loadScene(cine.sceneId,undefined,true);
    this.state.cinematic={
      steps:cine.steps,
      stepIndex:0,
      mode:null,
      waitMs:0,
      npcOverrides:new Map(),
      npcTargets:new Map(),
      activeNpcId:null,
      actionText:null,
      actionTimer:0,
      completionAction:cine.completionAction,
      completionValue:cine.completionValue,
    };
    this._executeCinematicStep(cine.steps[0]);
  }

  _executeCinematicStep(step){
    const cine=this.state.cinematic;
    if(!cine) return;
    cine.actionText=null;
    cine.activeNpcId=null;
    switch(step.type){
      case 'walk_to':{
        if(!step.characterId||step.characterId==='main-character'){
          const char=this.state.character,mc=this.project.mainCharacter;
          const scene=this.project.scenes.find(s=>s.id===this.state.currentSceneId);
          if(char&&mc&&scene){
            const path=findPath(scene.blockedZones||[],scene.width,scene.height,
              char.x+mc.width/2,char.y+mc.height/2,step.targetX??0,step.targetY??0,mc.width*(char.scale??1),mc.height*(char.scale??1));
            if(path.length>0){char.waypoints=path;char.waypointIndex=0;char.moving=true;}
          }
          cine.mode='walking_main';
        } else {
          const npcId=step.characterId;
          const scene=this.project.scenes.find(s=>s.id===this.state.currentSceneId);
          const npcObj=scene?.objects.find(o=>o.type==='character'&&o.npcId===npcId);
          const start=cine.npcOverrides.get(npcId)??{x:npcObj?.x??0,y:npcObj?.y??0};
          cine.npcOverrides.set(npcId,{...start});
          cine.npcTargets.set(npcId,{x:step.targetX??0,y:step.targetY??0});
          cine.activeNpcId=npcId;
          cine.mode='walking_npc';
        }
        break;
      }
      case 'talk':{
        const npc=step.characterId&&step.characterId!=='main-character'?(this.project.npcs||[]).find(n=>n.id===step.characterId):null;
        const speaker=npc?.name??(this.project.mainCharacter?.name??'Player');
        this.state.dialogText='['+speaker+']: '+(step.text??'');
        this.state.dialogCallback=()=>this._advanceCinematicStep();
        cine.mode='waiting_dialog';
        break;
      }
      case 'show_dialog':{
        this.state.dialogText=step.text??'';
        this.state.dialogCallback=()=>this._advanceCinematicStep();
        cine.mode='waiting_dialog';
        break;
      }
      case 'action':{
        const npc=step.characterId&&step.characterId!=='main-character'?(this.project.npcs||[]).find(n=>n.id===step.characterId):null;
        const actor=npc?.name??(this.project.mainCharacter?.name??'Player');
        cine.actionText=actor+' '+(step.actionLabel??'performs action');
        cine.actionTimer=2000;
        cine.mode='action';
        break;
      }
      case 'wait':{
        cine.waitMs=(step.duration??1)*1000;
        cine.mode='waiting';
        break;
      }
      case 'set_variable':{
        if(step.variable) this._applyVarExpr(step.variable);
        this._advanceCinematicStep();
        break;
      }
      case 'play_sound': this._advanceCinematicStep(); break;
    }
  }

  _advanceCinematicStep(){
    const cine=this.state.cinematic;
    if(!cine) return;
    cine.stepIndex++;
    if(cine.stepIndex>=cine.steps.length){this._completeCinematic();return;}
    this._executeCinematicStep(cine.steps[cine.stepIndex]);
  }

  _completeCinematic(){
    const cine=this.state.cinematic;
    if(!cine) return;
    const ca=cine.completionAction,cv=cine.completionValue;
    this.state.cinematic=null;
    switch(ca){
      case 'navigate_scene':{
        const s=this.project.scenes.find(s=>s.id===cv||s.name===cv);
        if(s) this._loadScene(s.id,undefined,true);
        break;
      }
      case 'show_dialog': this.state.dialogText=cv; break;
      case 'set_variable':{
        this._applyVarExpr(cv);
        break;
      }
    }
  }

  _updateCinematic(dt){
    const cine=this.state.cinematic;
    if(!cine||cine.mode===null) return;
    switch(cine.mode){
      case 'walking_main':{
        const char=this.state.character;
        if(!char||!char.moving) this._advanceCinematicStep();
        break;
      }
      case 'walking_npc':{
        const npcId=cine.activeNpcId;
        if(!npcId){this._advanceCinematicStep();break;}
        const pos=cine.npcOverrides.get(npcId);
        const target=cine.npcTargets.get(npcId);
        if(!pos||!target){this._advanceCinematicStep();break;}
        const dx=target.x-pos.x,dy=target.y-pos.y;
        const dist=Math.sqrt(dx*dx+dy*dy);
        const step=150*(dt/1000);
        if(dist<=step){pos.x=target.x;pos.y=target.y;this._advanceCinematicStep();}
        else{pos.x+=(dx/dist)*step;pos.y+=(dy/dist)*step;}
        break;
      }
      case 'waiting':{
        cine.waitMs-=dt;
        if(cine.waitMs<=0) this._advanceCinematicStep();
        break;
      }
      case 'action':{
        cine.actionTimer-=dt;
        if(cine.actionTimer<=0){cine.actionText=null;this._advanceCinematicStep();}
        break;
      }
      case 'waiting_dialog': break;
    }
  }

  _renderActionLabel(){
    const cine=this.state.cinematic;
    if(!cine||!cine.actionText) return;
    const{canvas,ctx}=this;
    const text=cine.actionText;
    const fontSize=20;
    ctx.font='bold '+fontSize+'px sans-serif';
    const w=ctx.measureText(text).width+32,h=44;
    const x=(canvas.width-w)/2,y=32;
    ctx.fillStyle='rgba(0,0,0,0.75)';
    ctx.beginPath();
    ctx.roundRect(x,y,w,h,8);
    ctx.fill();
    ctx.strokeStyle='#f97316';
    ctx.lineWidth=2;
    ctx.stroke();
    ctx.fillStyle='#fed7aa';
    ctx.textAlign='center';
    ctx.textBaseline='middle';
    ctx.fillText(text,canvas.width/2,y+h/2);
  }

  async _loadPhaser(){
    if(window.Phaser) return;
    return new Promise((resolve,reject)=>{
      const s=document.createElement('script');
      s.src='https://cdn.jsdelivr.net/npm/phaser@3.80.1/dist/phaser.min.js';
      s.onload=()=>resolve();s.onerror=reject;
      document.head.appendChild(s);
    });
  }

  async _loadMiniGameModule(source){
    const blob=new Blob([source],{type:'text/javascript'});
    const url=URL.createObjectURL(blob);
    const mod=await import(url);
    URL.revokeObjectURL(url);
    return mod.default;
  }

  async _launchMiniGame(action,isRepeat=false){
    const mg=(this.project.miniGames||[]).find(m=>m.id===action.value);
    if(!mg?.source) return;
    if(!isRepeat) this.repeatCounts.delete(action.id);
    const returnSceneId=this.state.currentSceneId;
    const snapshot={
      variables:{...this.state.variables},
      currentStageId:this.state.currentStageId,
      character:this.state.character?{...this.state.character,waypoints:[...this.state.character.waypoints]}:null,
      npcStates:new Map(Array.from(this.state.npcStates.entries()).map(([k,v])=>[k,{...v,waypoints:[...v.waypoints]}])),
      objectVisibility:new Map(this.objectVisibility),
      removedObjects:new Set(this.removedObjects),
      activeHotspots:new Set(this.state.activeHotspots),
      activeTeleportZones:new Set(this.state.activeTeleportZones),
      visitedScenes:[...this.state.visitedScenes],
      activeQuestIds:[...this.state.activeQuestIds],
      completedQuestIds:[...this.state.completedQuestIds],
    };
    this.state.miniGame={returnSceneId,instance:null};
    if(this.frameId!==null){cancelAnimationFrame(this.frameId);this.frameId=null;}
    try{
      await this._loadPhaser();
      const mod=await this._loadMiniGameModule(mg.source);
      const overlay=document.createElement('div');
      overlay.style.cssText='position:fixed;inset:0;z-index:9999;background:#000;display:flex;align-items:center;justify-content:center;';
      const canvas=document.createElement('canvas');
      canvas.width=800;canvas.height=600;
      overlay.appendChild(canvas);
      document.body.appendChild(overlay);
      const teardown=(result,vars)=>{
        this.state.miniGame?.instance?.destroy();
        this.state.miniGame=null;
        document.body.removeChild(overlay);
        this.state.currentSceneId=returnSceneId;
        this.state.currentStageId=snapshot.currentStageId;
        this.state.variables={...snapshot.variables};
        this.state.character=snapshot.character?{...snapshot.character,waypoints:[...snapshot.character.waypoints]}:null;
        this.state.npcStates=new Map(Array.from(snapshot.npcStates.entries()).map(([k,v])=>[k,{...v,waypoints:[...v.waypoints]}]));
        this.objectVisibility=new Map(snapshot.objectVisibility);
        this.removedObjects=new Set(snapshot.removedObjects);
        this.state.activeHotspots=new Set(snapshot.activeHotspots);
        this.state.activeTeleportZones=new Set(snapshot.activeTeleportZones);
        this.state.visitedScenes=[...snapshot.visitedScenes];
        this.state.activeQuestIds=[...snapshot.activeQuestIds];
        this.state.completedQuestIds=[...snapshot.completedQuestIds];
        this.state.dialogText=null;
        this.state.dialogCallback=null;
        if(vars) Object.assign(this.state.variables,vars);
        this.state.variables['minigame_result']=result;
        const resultActions=result==='win'?(action.onWinActions||[]):result==='lose'?(action.onLoseActions||[]):(action.onExitActions||[]);
        resultActions.forEach(a=>this._execAction(a));
        const hasAsyncAction=resultActions.some(a=>a.type==='launch_minigame');
        const repeatMatches=action.repeatOnResult==='any'||action.repeatOnResult===result;
        if(repeatMatches&&!hasAsyncAction){
          const count=this.repeatCounts.get(action.id)??0;
          const maxRepeats=action.repeatMax??0;
          if(maxRepeats===0||count<maxRepeats){
            this.repeatCounts.set(action.id,count+1);
            this._launchMiniGame(action,true);
            return;
          }
          this.repeatCounts.delete(action.id);
        }
        this.state.running=true;
        this.lastFrameTime=0;
        this._loop();
      };
      const spriteMap={};
      const spriteFrames={};
      for(const [slot,binding] of Object.entries(mg.spriteMap||{})){
        if(!binding?.sheetId) continue;
        const ss=(this.project.spriteSheets||[]).find(s=>s.id===binding.sheetId);
        if(!ss) continue;
        spriteMap[slot]=ss.imageUrl;
        if(binding.animId){
          const anim=(ss.animations||[]).find(a=>a.id===binding.animId);
          if(anim) spriteFrames[slot]={url:ss.imageUrl,frameWidth:ss.frameWidth,frameHeight:ss.frameHeight,startFrame:anim.startFrame,endFrame:anim.endFrame,frameRate:anim.fps,loop:anim.loop};
        }
      }
      const context={
        canvas,
        Phaser:window.Phaser,
        assets:(this.project.assets||[]).map(a=>({id:a.id,name:a.name,url:a.url,type:a.type})),
        spriteMap,
        spriteFrames,
        variables:{...this.state.variables},
        onComplete:(result,updatedVars)=>teardown(result,updatedVars),
      };
      const instance=mod.launch(context);
      if(this.state.miniGame) this.state.miniGame.instance=instance;
    }catch(err){
      console.error('Mini-game error:',err);
      this.state.miniGame=null;
      this.state.running=true;
      this.lastFrameTime=0;
      this._loop();
    }
  }

  _getCharSheet(facing){
    const mc=this.project.mainCharacter; if(!mc) return null;
    const cfg=mc.animations?.[facing]; if(!cfg?.spriteSheetId) return null;
    return this.project.spriteSheets?.find(s=>s.id===cfg.spriteSheetId)||null;
  }

  _getCharAnim(facing){
    const mc=this.project.mainCharacter; if(!mc) return null;
    const cfg=mc.animations?.[facing]; const sh=this._getCharSheet(facing);
    if(!sh||!cfg?.animationId) return null;
    return sh.animations.find(a=>a.id===cfg.animationId)||null;
  }

  _getAnimStartFrame(facing){ return this._getCharAnim(facing)?.startFrame??0; }

  _loadImage(url){
    if(this.imageCache.has(url)) return;
    const img=new Image(); img.onload=()=>this.imageCache.set(url,img); img.src=url;
  }
}
`.trim()
}
