/**
 * Returns the source of the standalone game engine as an ES-module string.
 * This is embedded verbatim as engine.js inside the exported Vite project ZIP.
 * It mirrors GameRuntime.ts with no external imports (plain JS, no TS).
 */
export function getStandaloneEngineSource(): string {
  return `
// Adventure Game Engine — standalone ES module (generated by Adventure Game Builder)

export class GameEngine {
  constructor(canvas, project) {
    this.canvas = canvas;
    this.ctx = canvas.getContext('2d');
    this.project = project;
    this.imageCache = new Map();
    this.objectVisibility = new Map();
    this.frameId = null;
    this.state = this._freshState();
    this._boundClick = this._handleClick.bind(this);
    this._boundMove = this._handleMouseMove.bind(this);
  }

  _freshState() {
    return {
      currentSceneId: this.project.settings?.startingSceneId || this.project.scenes[0]?.id || '',
      variables: {},
      visitedScenes: [],
      running: false,
      dialogText: null,
      dialogCallback: null,
    };
  }

  start() {
    if (this.state.running) return;
    this.state.running = true;
    this.canvas.addEventListener('click', this._boundClick);
    this.canvas.addEventListener('mousemove', this._boundMove);
    this._loadScene(this.state.currentSceneId);
    this._loop();
  }

  stop() {
    this.state.running = false;
    this.canvas.removeEventListener('click', this._boundClick);
    this.canvas.removeEventListener('mousemove', this._boundMove);
    if (this.frameId !== null) { cancelAnimationFrame(this.frameId); this.frameId = null; }
  }

  reset() {
    this.stop();
    this.objectVisibility.clear();
    this.imageCache.clear();
    this.state = this._freshState();
    this.start();
  }

  _loadScene(sceneId) {
    this.state.currentSceneId = sceneId;
    if (!this.state.visitedScenes.includes(sceneId)) this.state.visitedScenes.push(sceneId);
    const scene = this.project.scenes.find(s => s.id === sceneId);
    if (scene) {
      if (scene.backgroundImageUrl) this._loadImage(scene.backgroundImageUrl);
      scene.objects.forEach(o => { if (o.imageUrl) this._loadImage(o.imageUrl); });
    }
    this.project.events
      .filter(e => e.sceneId === sceneId && e.trigger === 'enter' && e.enabled)
      .forEach(ev => this._execEvent(ev));
  }

  _loop() {
    if (!this.state.running) return;
    this._render();
    this.frameId = requestAnimationFrame(() => this._loop());
  }

  _render() {
    const { canvas, ctx } = this;
    const scene = this.project.scenes.find(s => s.id === this.state.currentSceneId);
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    if (!scene) {
      ctx.fillStyle = '#1a1a2e'; ctx.fillRect(0,0,canvas.width,canvas.height);
      ctx.fillStyle = '#e2e8f0'; ctx.font = '20px sans-serif';
      ctx.textAlign = 'center'; ctx.textBaseline = 'middle';
      ctx.fillText('No scene', canvas.width/2, canvas.height/2);
      return;
    }
    const sx = canvas.width / scene.width, sy = canvas.height / scene.height;
    ctx.save(); ctx.scale(sx, sy);
    ctx.fillStyle = scene.backgroundColor || '#000';
    ctx.fillRect(0, 0, scene.width, scene.height);
    if (scene.backgroundImageUrl) {
      const img = this.imageCache.get(scene.backgroundImageUrl);
      if (img) ctx.drawImage(img, 0, 0, scene.width, scene.height);
    }
    [...scene.objects].sort((a,b) => a.zIndex - b.zIndex).forEach(obj => {
      const vis = this.objectVisibility.has(obj.id) ? this.objectVisibility.get(obj.id) : obj.visible;
      if (!vis) return;
      ctx.save(); ctx.globalAlpha = obj.opacity;
      const img = obj.imageUrl ? this.imageCache.get(obj.imageUrl) : null;
      if (img) {
        ctx.drawImage(img, obj.x, obj.y, obj.width, obj.height);
      } else {
        const colors = { sprite:'#4f46e5', character:'#7c3aed', item:'#d97706', hotspot:'rgba(99,102,241,0.25)', background:'#1e293b' };
        ctx.fillStyle = colors[obj.type] || '#4f46e5';
        ctx.fillRect(obj.x, obj.y, obj.width, obj.height);
        if (obj.type !== 'hotspot') {
          ctx.fillStyle = '#fff'; ctx.font = '14px sans-serif';
          ctx.textAlign = 'center'; ctx.textBaseline = 'middle';
          ctx.fillText(obj.name, obj.x+obj.width/2, obj.y+obj.height/2);
        }
      }
      ctx.restore();
    });
    ctx.restore();
    if (this.state.dialogText) this._renderDialog();
  }

  _renderDialog() {
    const { canvas, ctx } = this;
    const pad = 24, bh = 130, by = canvas.height - bh - 12;
    ctx.fillStyle = 'rgba(0,0,0,0.88)'; ctx.fillRect(8,by,canvas.width-16,bh);
    ctx.strokeStyle = '#6366f1'; ctx.lineWidth = 2; ctx.strokeRect(8,by,canvas.width-16,bh);
    const fs = Math.max(12, Math.min(16, canvas.width/50));
    ctx.font = fs+'px sans-serif'; ctx.fillStyle = '#e2e8f0';
    ctx.textAlign = 'left'; ctx.textBaseline = 'top';
    const mw = canvas.width-16-pad*2, words = this.state.dialogText.split(' ');
    let line='', ly=by+pad, lh=fs+6;
    words.forEach(w => {
      const t = line+w+' ';
      if (ctx.measureText(t).width > mw && line) { ctx.fillText(line.trim(), 8+pad, ly); line=w+' '; ly+=lh; }
      else line=t;
    });
    if (line.trim()) ctx.fillText(line.trim(), 8+pad, ly);
    ctx.fillStyle='#6366f1'; ctx.font='12px sans-serif'; ctx.textAlign='right'; ctx.textBaseline='bottom';
    ctx.fillText('▶ Click to continue', canvas.width-16, by+bh-8);
  }

  _scenePos(e) {
    const r = this.canvas.getBoundingClientRect();
    const cx = (e.clientX-r.left)*(this.canvas.width/r.width);
    const cy = (e.clientY-r.top)*(this.canvas.height/r.height);
    const scene = this.project.scenes.find(s=>s.id===this.state.currentSceneId);
    if (!scene) return {x:cx,y:cy};
    return { x: cx/(this.canvas.width/scene.width), y: cy/(this.canvas.height/scene.height) };
  }

  _handleClick(e) {
    if (this.state.dialogText) {
      this.state.dialogText=null;
      const cb=this.state.dialogCallback; this.state.dialogCallback=null; if(cb)cb();
      return;
    }
    const pos = this._scenePos(e);
    const scene = this.project.scenes.find(s=>s.id===this.state.currentSceneId);
    if (!scene) return;
    const obj = this._objAt(scene, pos.x, pos.y);
    if (!obj) return;
    this.project.events
      .filter(ev=>ev.sceneId===scene.id&&ev.objectId===obj.id&&ev.trigger==='click'&&ev.enabled)
      .forEach(ev=>this._execEvent(ev));
  }

  _handleMouseMove(e) {
    if (this.state.dialogText) return;
    const pos = this._scenePos(e);
    const scene = this.project.scenes.find(s=>s.id===this.state.currentSceneId);
    if (!scene) return;
    this.canvas.style.cursor = this._objAt(scene, pos.x, pos.y) ? 'pointer' : 'default';
  }

  _objAt(scene, x, y) {
    return [...scene.objects]
      .filter(o => (this.objectVisibility.has(o.id)?this.objectVisibility.get(o.id):o.visible))
      .sort((a,b)=>b.zIndex-a.zIndex)
      .find(o=>x>=o.x&&x<=o.x+o.width&&y>=o.y&&y<=o.y+o.height)||null;
  }

  _execEvent(ev) { ev.actions.forEach(a=>this._execAction(a)); }

  _execAction(action) {
    switch(action.type) {
      case 'navigate_scene': {
        const s=this.project.scenes.find(s=>s.id===action.value||s.name===action.value);
        if(s) this._loadScene(s.id); break;
      }
      case 'show_dialog': this.state.dialogText=action.value; break;
      case 'set_variable': {
        const i=action.value.indexOf('=');
        if(i!==-1) this.state.variables[action.value.slice(0,i).trim()]=action.value.slice(i+1).trim();
        break;
      }
      case 'show_object': this.objectVisibility.set(action.value,true); break;
      case 'hide_object': this.objectVisibility.set(action.value,false); break;
      case 'play_sound': {
        const a=this.project.assets?.find(a=>a.id===action.value||a.name===action.value);
        if(a?.url) new Audio(a.url).play().catch(()=>{});
        break;
      }
    }
  }

  _loadImage(url) {
    if (this.imageCache.has(url)) return;
    const img=new Image(); img.onload=()=>this.imageCache.set(url,img); img.src=url;
  }
}
`.trim()
}
